name: task_buddy
description: A task management app that allows users to create, update, and delete tasks, set deadlines, and categorize them. Uses Appwrite for user authentication, data storage, and real-time updates.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts:
  go_router: ^7.1.1
  flutter_svg: ^2.0.6
  flutter_animate: ^4.1.1+1
  appwrite: ^9.0.0
  rive:
  carousel_slider:
  smooth_page_indicator:
  flutter_riverpod:
  loading_indicator:
  intl: ^0.18.1
  flutter_slidable: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
      - assets/icons/
      - assets/rive_assets/